core/urls.py
from django.urls import path
from .views import (
    HomeView,
    MockUpDetailView,
    MockUpListView,

    download_counter,

    aboutus,
    UseFullListView,

    mockup_like,

    UserProfile,
    UpdateUserProfileView,
)
app_name = "core"

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('home/<slug:slug>/', HomeView.as_view(), name="home"),
    path("detail/<slug:slug>/", MockUpDetailView.as_view(), name="detail"),
    
    path("mockups/", MockUpListView.as_view(), name="mockup"),
    path("mockups/<slug:slug>/", MockUpListView.as_view(), name="mockup"),

    path('ajax/download_counter/', download_counter, name='download_counter'),

    path("about-us/", aboutus, name="aboutus"),
    path("usefull-page/", UseFullListView.as_view(), name="usefull"),   

    path('ajax/like/mockup/', mockup_like, name='likes'), 

    path('profile/', UserProfile.as_view(), name='user-profile'),
    path('update/profile/<int:pk>/', UpdateUserProfileView.as_view(), name='update-profile'),
]

mockup_uz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('mockup.uz/admin/page/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),

    path('', include('core.urls', namespace="core")),
    path('product/', include('product.urls', namespace="product")),
    path('accounts/', include('users.urls', namespace='users')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import (
    PhoneNumberView,
    PhoneNumberVerificationView,
    SignUpView,
    LoginView,
    LogOutView,

    password_reset_phonenumber,
    password_reset_verification,
    password_reset_newpassword,

    change_password,
)

app_name = "users"

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name="logout"),
    path('phone/number/', PhoneNumberView.as_view(), name='phone-number-view'),
    path('phone/confirmation/<str:key>/', PhoneNumberVerificationView.as_view(), name='phone-verification'),
    path('create/account/<str:key>/', SignUpView.as_view(), name='signup-view'),

    path('reset/password/phonenumber/', password_reset_phonenumber, name='reset-password-phonenumber'),
    path('reset/password/verification/<str:key>/', password_reset_verification, name='reset-password-verification'),
    path('reset/password/newpassword/<str:key>/', password_reset_newpassword, name='reset-password-newpassword'),

    path('change/password/<int:pk>/', change_password, name='change-password'),

]

templates/includes/footer.html
{% load static %}

<footer class="container-fluid pt-5 pb-2 border-top bg-light">
	<div class="container">
		<div class="row text-dark text-center">
		 	<div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
				<a href="#!" class=""><img class="pb-3" src="{% static 'img/logo.svg' %}" width="200"></a>
			 	<ul class="list-unstyled">
				 	<li><a href="/" class="text-dark text-decoration-none">Asosiy</a></li>
				 	<li><a href="{% url 'core:aboutus' %}" class="text-dark text-decoration-none">Biz haqimizda</a></li>
				 	<li><a href="{% url 'core:mockup' %}" class="text-dark text-decoration-none">Muckup</a></li>
				 	<li><a href="{% url 'core:usefull' %}" class="text-dark text-decoration-none">Foydali</a></li>
			 	</ul>
		 	</div>
		 	<div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
				<ul class="list-unstyled pb-2">
				 	<li class=""><a href="products.html" class="text-dark text-decoration-none">3D Model</a></li>
				 	<li class=""><a href="products.html" class="text-dark text-decoration-none">Fudbolkalar</a></li>
				 	<li class=""><a href="products.html" class="text-dark text-decoration-none">Buyumlar</a></li>
				 	<li class=""><a href="products.html" class="text-dark text-decoration-none">Avtomobillar</a></li>
				 	<li class=""><a href="products.html" class="text-dark text-decoration-none">Sumka</a></li>
				 	<li class=""><a href="products.html" class="text-dark text-decoration-none">Kepka</a></li>
			 	</ul> 
			</div>
			<div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3">
				<ul class="list-unstyled pb-2">
					<li><a href="products.html" class="text-dark text-decoration-none">Kitob</a></li>
					<li><a href="products.html" class="text-dark text-decoration-none">Soat</a></li>
					<li><a href="products.html" class="text-dark text-decoration-none">Brelok</a></li>
					<li><a href="products.html" class="text-dark text-decoration-none">Avtomobillar</a></li>
					<li><a href="products.html" class="text-dark text-decoration-none">Krushka</a></li>
					<li><a href="products.html" class="text-dark text-decoration-none">Qurilmalar</a></li>
				</ul>
			</div>
		 	<div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3 text-center">
				<a href="#!"><span class="youtube"><i class="fa fa-youtube mr-2"></i></span></a>
				<a href="#!"><span class="telegram"><i class="fa fa-telegram mr-2"></i></span></a>
				<a href="#!"><span class="instagram"><i class="fa fa-instagram mr-2"></i></span></a>
				<a href="#!"><span class="facebook"><i class="fa fa-facebook-square mr-2"></i></span></a>
		 	</div>
		</div>
		<div class="row border-top pt-3 text-secondary">
			<div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 text-center text-sm-center text-md-left text-lg-left text-xl-left">
				{% now 'Y' as year %}
				<small>©{{ year }} Barcha huquqlar himoyalangan.</small>
			</div>
			<div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 text-center text-sm-center text-md-right text-lg-right text-xl-right">
				<small class="pr-3">Sayt MYWEB.UZ studiyasida ishlab chiqilgan.</small>
			</div>
		</div>
	</div>
</footer>

templates/includes/header.html
{% load static %}
{% load i18n %}

<header class="container-fluid pl-0 pr-0 fixed-top bg-light" >
	<nav class="container navbar navbar-expand-lg navbar-light text-center pl-0 pr-0">
		<a class="navbar-brand pl-2" href="/"><img src="{% static 'img/logo.svg' %}" class="headerLogo"></a>
		<button class="navbar-toggler m-2" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav ml-auto pt-2">
				<li class="nav-item">
					<a class="nav-link active h5  bestFont2 text-dark pr-3 pl-3" aria-current="page" href="/">{% trans 'Asosiy' %}</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active h5  bestFont2 text-dark pr-3 pl-3" href="{% url 'core:aboutus' %}">{% trans 'Biz haqimizda' %}</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active h5  bestFont2 text-dark pr-3 pl-3" href="{% url 'core:mockup' %}">{% trans 'Kategoriya' %}</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active h5  bestFont2 text-dark pr-3 pl-3" href="{% url 'core:usefull' %}">{% trans 'Foydali' %}</a>
				</li>
			</ul>
			<form class="socialIconHeader form-inline justify-content-center pb-3 pt-3">
				<div class="dropdown">
					<img src="{% static 'img/user.svg' %}" width="35" height="35" class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					<div class="dropdown-menu  dropdown-menu-lg-right dropdown-menu-xl-right text-center" aria-labelledby="dropdownMenuButton">
						{% if user.is_staff %}
							<a class="dropdown-item" href="mockup.uz/admin/page/">{% trans 'Admin' %}</a>
							<a class="dropdown-item" href="{% url 'core:user-profile' %}">{% trans 'My Profile' %}</a>
							<a class="dropdown-item" href="{% url 'users:logout' %}?next={{ request.path }}">{% trans 'Logout' %}</a>
						{% elif user.is_authenticated %}
							<a class="dropdown-item" href="{% url 'core:user-profile' %}">{% trans 'My Profile' %}</a>
							<a class="dropdown-item" href="{% url 'users:logout' %}?next={{ request.path }}">{% trans 'Logout' %}</a>
						{% else %}
							<a class="dropdown-item" href="{% url 'users:login' %}?next={{ request.path }}">{% trans 'Login' %}</a>
							<a class="dropdown-item" href="{% url 'users:phone-number-view' %}">{% trans 'Sign up' %}</a>
						{% endif %}
					</div>
				</div>
			</form>   
		</div>
	</nav>
</header>

templates/includes/messages.html
<!-- <h1>hello Jamshid</h1> -->

{% if messages %}
    <ul>
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message|safe }}
                <input type='hidden' id='message_tag' value='{{ message.tags }}'>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    </ul>
{% endif %}

templates/includes/pagination.html
<div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 p-3 text-center">
    <nav aria-label="Page navigation example" class="navbar">
        <ul class="pagination pagination-md m-auto">
            <li class="page-item">
                {% if page_obj.has_previous %}
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                {% else %}
                    <a class="page-link" href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Previous</span>
                    </a>
                {% endif %}
            </li>

            {% for index in page_obj.paginator.page_range %}
                {% if page_obj.number == index %}
                    <li class="page-item active"><a class="page-link" href="?page={{ index }}">{{ index }}</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ index }}">{{ index }}</a></li>
                {% endif %}
            {% endfor %}

            <li class="page-item">
                {% if page_obj.has_next %}
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                {% else %}
                    <a class="page-link" href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Next</span>
                    </a>
                {% endif %}
                
            </li>
        </ul>
    </nav>
</div>