core/urls.py
from django.urls import path
from .views import (
    HomeView,
    MockUpDetailView,
    MockUpListView,

    download_counter,

    aboutus,
    UseFullListView,

    mockup_like,

    UserProfile,
    UpdateUserProfileView,
)
app_name = "core"

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('home/<slug:slug>/', HomeView.as_view(), name="home"),
    path("detail/<slug:slug>/", MockUpDetailView.as_view(), name="detail"),
    
    path("mockups/", MockUpListView.as_view(), name="mockup"),
    path("mockups/<slug:slug>/", MockUpListView.as_view(), name="mockup"),

    path('ajax/download_counter/', download_counter, name='download_counter'),

    path("about-us/", aboutus, name="aboutus"),
    path("usefull-page/", UseFullListView.as_view(), name="usefull"),   

    path('ajax/like/mockup/', mockup_like, name='likes'), 

    path('profile/', UserProfile.as_view(), name='user-profile'),
    path('update/profile/<int:pk>/', UpdateUserProfileView.as_view(), name='update-profile'),
]

mockup_uz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('mockup.uz/admin/page/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),

    path('', include('core.urls', namespace="core")),
    path('product/', include('product.urls', namespace="product")),
    path('accounts/', include('users.urls', namespace='users')),
] 
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

app_name = "product"

urlpatterns = [
    
]

users/urls.py
from django.urls import path
from .views import (
    PhoneNumberView,
    PhoneNumberVerificationView,
    SignUpView,
    LoginView,
    LogOutView,

    password_reset_phonenumber,
    password_reset_verification,
    password_reset_newpassword,

    change_password,
)

app_name = "users"

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name="logout"),
    path('phone/number/', PhoneNumberView.as_view(), name='phone-number-view'),
    path('phone/confirmation/<str:key>/', PhoneNumberVerificationView.as_view(), name='phone-verification'),
    path('create/account/<str:key>/', SignUpView.as_view(), name='signup-view'),

    path('reset/password/phonenumber/', password_reset_phonenumber, name='reset-password-phonenumber'),
    path('reset/password/verification/<str:key>/', password_reset_verification, name='reset-password-verification'),
    path('reset/password/newpassword/<str:key>/', password_reset_newpassword, name='reset-password-newpassword'),

    path('change/password/<int:pk>/', change_password, name='change-password'),

]

product/models.py
from django.urls import reverse

# Create your models here.
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth import get_user_model

User = get_user_model()
# from users.models import User
# Create your models here.



class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name="Name")
    slug = models.SlugField(max_length=250, verbose_name="Slug")

    image = models.ImageField(upload_to="category-image/%d/%m/%Y/", blank=True, null=True, verbose_name="Image")
    caption = models.CharField(max_length=300, blank=True, null=True, verbose_name="Caption")

    active = models.BooleanField(default=False, verbose_name='Active Category')

    class Meta:
        ordering = ['name', ]
    
    def __str__(self):
        return self.name
    
    @property
    def imageURL(self):
        try:
            url=self.image.url
        except:
            url=''
        return url
    


class Tag(models.Model):
    # category = models.ManyToManyField(Category, verbose_name="Category")
    tag = models.CharField(max_length=50, verbose_name="Tag Name")

    def __str__(self):
        return self.tag


class UserViews(models.Model):
    mockup = models.ForeignKey('Product', on_delete=models.CASCADE, related_name="product_views", verbose_name="Product")
    visitor_ip = models.GenericIPAddressField(default='0.0.0.0')

    def __str__(self):
        return f"{self.visitor_ip} on {self.mockup.name}"


class Product(models.Model):
    category = models.ForeignKey(Category, blank=True, null=True, on_delete=models.SET_NULL, related_name='product_category', verbose_name="Category")

    file       = models.FileField(upload_to="mockup-file/%d/%m/%Y/", null=True, verbose_name="MockUp File")
    resolution = models.CharField(max_length=50, blank=True, null=True, verbose_name="Resolution")
    extension  = models.CharField(max_length=10, blank=True, null=True, verbose_name="Extension")

    name        = models.CharField(max_length=200, verbose_name="Name")
    slug        = models.SlugField(max_length=300, unique=True, verbose_name="Slug")
    description = models.TextField(verbose_name="Description")
    price       = models.FloatField(blank=True, null=True, validators=(MinValueValidator(0), MaxValueValidator(100000000)), verbose_name="Price")
    discount    = models.FloatField(blank=True, null=True, validators=(MinValueValidator(0), MaxValueValidator(100000000)), verbose_name="Discount")
    paid        = models.BooleanField(default=True, verbose_name="Paid")
    free        = models.BooleanField(default=False, verbose_name="Free") 

    downloaded = models.SmallIntegerField(default=0)
    # viewed = models.SmallIntegerField(default=0)

    liked = models.ManyToManyField(User, blank=True, null=True, related_name="user_likes",)
    tags  = models.ManyToManyField(Tag, related_name="product_tags", verbose_name="Product Tags")

    published_at = models.DateTimeField(auto_now_add=True)
    updated_at   = models.DateTimeField(auto_now=True)

    def __str_(self):
        return self.name + " | " + self.category.name

    def get_absolute_url(self):
        return reverse("core:detail", kwargs = {"slug": self.slug})
    
    @property
    def fileURL(self):
        try:
            url = self.file.url
        except:
            url=''
        return url
    
    @property
    def get_extension(self):
        import os
        name, extension = os.path.splitext(self.file.name)
        return extension

    @property
    def date(self):
        if self.published_at == self.updated_at:
            date = self.published_at
        else:
            date = self.updated_at
        return date

    @property
    def views_count(self):
        return UserViews.objects.filter(mockup=self).count()
    
    @property
    def total_like(self):
        return self.liked.count()


class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_image", verbose_name="Product")
    
    image = models.ImageField(upload_to="product-image/%d/%m/%Y/", verbose_name="Image")
    caption = models.CharField(max_length=300, blank=True, null=True, verbose_name="Caption")

    def __str__(self):
        return "image pk: "+str(self.pk)+self.product.name
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url=''
        return url        


class MockUp(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_file", verbose_name="Product")

    file = models.FileField(upload_to="mockup-file/%d/%m/%Y/", verbose_name="MockUp File")
    resolution = models.CharField(max_length=50, blank=True, null=True, verbose_name="Resolution")
    extension = models.CharField(max_length=10, blank=True, null=True, verbose_name="Extension")

    def __str__(self):
        return "File pk: "+str(self.pk)+self.product.name
    @property
    def fileURL(self):
        try:
            url = self.file.url
        except:
            url=''
        return url
    
    @property
    def get_extension(self):
        import os
        name, extension = os.path.splitext(self.file.name)
        return extension

users/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import ugettext_lazy as _
from django.db.models.signals import post_save
from django.utils import timezone
import binascii
import os

from .manager import UserManager

class User(AbstractBaseUser, PermissionsMixin):
    image            = models.ImageField(_('Image'), upload_to='user-image/', blank=True, null=True)
    full_name        = models.CharField(_('Full Name'), max_length=255, null=True)
    phone_number     = PhoneNumberField(_('Phone Number'), unique=True)
    email            = models.EmailField(_('Email'), blank=True, null=True)
    address          = models.CharField(_('Address'), max_length=255, blank=True, null=True)
    company          = models.CharField(_('Company'), max_length=255, blank=True, null=True)
    company_web_site = models.URLField(_('Company Web Site'), blank=True, null=True)
    company_address  = models.CharField(_('Company Address'), max_length=255, blank=True, null=True)

    is_staff              = models.BooleanField(_('is_staff'), default=False)
    is_superuser          = models.BooleanField(_('is_superuser'), default=False)
    is_active             = models.BooleanField(_('is_active'), default=True)
    last_login            = models.DateTimeField(_('last_login'), auto_now=True, null=True, blank=True)
    date_joined           = models.DateTimeField(_("date_joined"), auto_now_add=True)
    phone_number_verified = models.BooleanField(default=False)
    change_pw             = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD     = 'phone_number'
    PHONE_NUMBER_FIELD = 'phone_number'
    # REQUIRED_FIELDS    = ['full_name',]

    class Meta:
        ordering            = ('phone_number',)
        verbose_name        = _('User')
        verbose_name_plural = _('Users')

    def __str__(self):
        if self.full_name:
            return self.full_name +" | " + str(self.phone_number) 
        return str(self.phone_number)

    def get_absolute_url(self):
        return "/users/%i/" % (self.pk)
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url=''
        return url

def post_save_user_receiver(sender, instance, created, **kwargs):
    phone_number = instance
    if created:
        user = User.objects.get(phone_number=instance.phone_number)
        user.phone_number_verified = True

post_save.connect(post_save_user_receiver, sender=User)


class CustomToken(models.Model):
    """
    The default authorization token model.
    """
    key               = models.CharField(_("Key"), max_length=40, unique=True)
    phone_number      = PhoneNumberField(_('Phone Number'))
    confirmation_code = models.SmallIntegerField(_('Confirmation Code'), blank=True, null=True)
    session_key       = models.CharField(_("Session Key"), max_length=200, blank=True, null=True)
    client_ip         = models.CharField(_("Client Ip"), max_length=50, blank=True, null=True)

    created = models.DateTimeField(_("Created"), default=timezone.now)

    class Meta:
        verbose_name = _("Token")
        verbose_name_plural = _("Tokens")

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = self.generate_key()
            while 1:
                if CustomToken.objects.filter(key=self.key).exists():
                    self.key = self.generate_key()
                else:
                    break
        return super(CustomToken, self).save(*args, **kwargs)

    def generate_key(self):
        return binascii.hexlify(os.urandom(20)).decode()

    def __str__(self):
        return self.key
    
    @property
    def check_valid_token(self):
        if self.created < timezone.now()-timezone.timedelta(minutes=5):
            e = CustomToken.objects.get(pk=self.pk)
            e.delete()
            return False
        else:
            return True

product/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta property="og:image" content="http://senat.uz/frontend/web/images/gerb.png">

		{% block title %} <title>muckup.uz</title> {% endblock title %}

		{% block css %}

		{% endblock css %}

		<script>
			window.dataLayer = window.dataLayer || [];
			function gtag(){dataLayer.push(arguments);}
			gtag('js', new Date());
		
			gtag('config', 'UA-188496439-1');
			</script>
		
			
			<script type="text/javascript">
			  var user = '{{request.user}}'
		
			  function getToken(name) {
				var cookieValue = null;
				if (document.cookie && document.cookie !== '') {
				  var cookies = document.cookie.split(';');
				  for (var i = 0; i < cookies.length; i++) {
					var cookie = cookies[i].trim();
					// Does this cookie string begin with the name we want?
					if (cookie.substring(0, name.length + 1) === (name + '=')) {
					  cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
					  break;
					}
				  }
				}
				return cookieValue;
			  }
			  var csrftoken = getToken('csrftoken')
		
			  function getCookie(name) {
				// Split cookie string and get all individual name=value pairs in an array
				var cookieArr = document.cookie.split(";");
		
				// Loop through the array elements
				for(var i = 0; i < cookieArr.length; i++) {
				  var cookiePair = cookieArr[i].split("=");
		
				  /* Removing whitespace at the beginning of the cookie name
				  and compare it with the given string */
				  if(name == cookiePair[0].trim()) {
					// Decode the cookie value and return
					return decodeURIComponent(cookiePair[1]);
				  }
				}
		
				// Return null if not found
				return null;
			  }
			
			</script>

	</head>
	<body>

		{% include 'includes/header.html' %} 

		{% block body %}
	
		{% endblock body %}

		{% include 'includes/footer.html' %}


	<!-- <div class="fakeLoader"></div> -->
	<button class="btn btn-outline-danger btn-top" title="ScrollTop"><i class="fa fa-angle-up"></i></button>

		{% block js %}
		
		{% endblock js %}
		<script src="{% static 'js/js-methods.js' %}"></script>

	</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

	{% block css %}
		<link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/fakeLoader.min.css' %}">
		
		<link rel="stylesheet" href="{% static 'css/swiper-bundle.min.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

		<style>
			.swiper-container{
				width:100%;
				overflow:hidden;
				height:80vh;
			} 
		
			.swiper-slide{
		
				overflow:hidden;
				width: 1920px;
			}
			@media (max-width:576px) {
    		  .swiper-container {
     			   height: 250px;
     			 }
   				}

  			@media (min-width: 576px) and (max-width: 768px) {
      			.swiper-container {
        			height: 350px;
     				}
    			}
    		@media (min-width: 768px) and (max-width: 992px) {
      			.swiper-container {
        			height: 400px;
     				}
    			}
			@media (min-width: 992px) and (max-width: 1200px) {
      			.swiper-container {
        			height: 550px;
     			}
    		}
			@media (min-width: 1200px) {
      			.swiper-container {
        			height: 600px;
     			}
    		}
			/* Dropdown Button */

			.dropdown {
				position: relative;
				display: inline-block;
			}
			.dropdown-content {
				display: none;
				position: absolute;
				background-color: #ffffff;
				min-width: 160px;
				box-shadow: 0px 8px 20px 1px rgba(0,0,0,0.2);
				z-index: 1;
			}
			.dropdown-content a {
				color: black;
				padding: 12px 16px;
				text-decoration: none;
				display: block;
			}
			.dropdown-content a:hover {background-color: #ddd;}
			.dropdown:hover .dropdown-content {display: block;}
			.dropbtn{
				color: #000;
			}
			.dropdown:hover .dropbtn {
				background-color: #3e8e41;
				color: #ffffff;
			}
		</style>

	{% endblock css %}

	{% block body %}

		<section class="container-fluid pl-0 pr-0" style="margin-top: 70px;">
			<div class="swiper-container" >
				<div class="swiper-wrapper" >  
					<div class="swiper-slide" style="background-image: url(/static/img/header1.jpg); background-repeat: no-repeat; background-size: cover;">
						<div class="carousel-caption text-left "> 
						</div>
					</div>
					<div class="swiper-slide" style="background-image: url(/static/img/sds.jpg); background-repeat: no-repeat; background-size: cover;">
						<div class="carousel-caption text-left"> 
						</div>
					</div>
					<div class="swiper-slide pt-5" style="background-image: url(/static/img/dfd5.jpg); background-repeat: no-repeat; background-size: cover;">
						<div class="carousel-caption text-left"> 
						</div>
					</div>
				</div>
			</div>
		</section>
		

		<section class="container-fluid pt-5">
			<div class="container pl-0 pr-0">
				<div class="row border pt-2 pb-2">
					<div class="col-12 col-md-4 col-lg-3 col-xl-2 pt-4 pb-1 pl-2 mb-4 text-center">
						<div class="dropdown">
							<a href="#!" class="text-decoration-none h4 dropbtn border p-2">Kategoriya<i class="fa fa-angle-down"></i></a>
							<div class="dropdown-content" style="z-index: 9999; margin-top: 7px;">

								{% for category in category_list %}
									<a href="{% url 'core:home' category.slug %}" class="text-decoration-none text-dark border-bottom pt-2 pb-2">{{ category.name }}</a>
								{% endfor %}

							</div>
						</div>
					</div>
					<div class="col-12 col-md-8 col-lg-9 col-xl-10 pt-3 pb-2 pl-2 text-center">
						<div class="row">
							
							{% for category in category_list %}
								{% if category.active %}
									<div class="col-6 col-sm-4 col-md-3 col-lg-2 col-xl-1 pl-0 pr-0 text-center"><a class="text-dark h6 m-auto text-decoration-none" href="{% url 'core:home' category.slug %}">
										<img src="{{ category.imageURL }}" width="30" height="30"  alt=""><h6>{{ category.name }}</h6></a>
									</div>
								{% endif %}
							{% endfor %}

						</div>
					</div>
				</div>
			</div>
		</section>


		<section class="container pl-0 pr-0 searchSection pt-5 pb-5">
			<div class="container">
				<div class="row">
					<div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
						<h2 class="font-weight-bold">Top mackup</h2>
					</div>
					<div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">

						{% include 'includes/messages.html' %}

						<!-- Search Bar -->
						<form method="GET" class="search" style="border: 1px solid #ddd; border-radius: 50px; padding-left: 20px; padding-right: 3px;">
							<input name='q' type="text" class="p-0 m-0" placeholder="Izlash ...." required>
							<div class="button-src">
								<button type="submit" class="btn">Izlash</button>
							</div>
						</form>
						<!-- Search Bar -->

					</div>
				</div>
			</div>
		</section>


		<section class="container p-3 p-lg-0 p-xl-0 text-center">
			<div class="row" id="ads">
				{% for obj in object_list %}
					<div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 p-3">
						<div class="card rounded profile-card">
							<div class="card-image">
								<span class="card-notify-badge ml-3">{{ obj.category }}</span>
								<!-- Price -->
								{% if obj.free %}
									<span class="card-notify-year">Free</span>
								{% elif obj.discount %}
									<small><del>{{ obj.price }}</del></small>
									<span class="card-notify-year">{{ obj.discount }}</span>
								{% elif obj.price %}
									<span class="card-notify-year">{{ obj.price }}</span>
								{% else %}
									<span class="card-notify-year">Free</span>
								{% endif %}
								<!-- End Price -->

								{% for image in obj.product_image.all %}
									{% if forloop.counter == 1 %}
										<img class="img-flu" src="{{ image.imageURL }}" width="100%" height="300" alt="Alternate Text" />
									{% endif %}
								{% endfor %}

							</div>
							<div class="card-body text-center">
								<div class="ad-title m-auto">
									<h6>{{ obj.name|truncatechars:20 }}</h6>
								</div>
							</div>
							<div class="profile-content">
								<ul class="social-link">
									<a href="{{ obj.fileURL }}" onclick="core_method_js(this)" data-slug="{{ obj.slug }}" class="text-white"><i class="fa fa-download fa-2x mr-2"></i></a>
									<a href="{% url 'core:detail' obj.slug %}" class="text-white heartBtn"><i class="fa fa-eye fa-2x mr-2 "></i></a>
									
									{% if request.user in obj.liked.all %}
										<a  onclick="like_unlike(this)" data-slug="{{ obj.slug }}" class="text-white heartIcon"><i style='color: red;' class="fa fa-heart fa-2x"></i></a>
									{% else %}
										<a onclick="like_unlike(this)" data-slug="{{ obj.slug }}" class="text-white heartIcon"><i class="fa fa-heart fa-2x"></i></a>
									{% endif %}
								</ul>
							</div>
						</div>
					</div>
				{% empty %}
					<div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 pb-4">
						<div class="profile-card card shadow-lg border-0">
							<h5 class="card-title pl-3 pr-3 pb-2">There is no available mockup ;)</h5>
						</div>
					</div>
				{% endfor %}

				
				<div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 p-3">
					<a href="{% url 'core:mockup' %}" class="btn border pl-5 pr-5 font-weight-bold" style="letter-spacing: 2.5px; background-color: #efefef; box-shadow: #efefef 0px 0px 10px 5px;">Yanada ko'proq</a>
				</div>
			</div>
		</section> 

		<section class="container-fluid">
			<div class="container">
				<div class="row">

				</div>
			</div>
		</section>


		<section class="container-fluid sectionBlogImg mt-5">
			<div class="container">
				<div class="row">
					<div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 pt-4 pb-4">
						<div class="pt-5 pb-5">
						<h3 class="bestFont font-weight-bold sectionText1">Barchasini birdaniga oling!</h3>
						<h5 class="bestFont font-weight-bold  sectionText2 mt-3">Siz bu servis orqali tizimda joylashgan barcha mackup fayllarini bir vaqtning o'zida olishingiz mumkin.</h5>
						<a href="" class="btn bestFont mt-4" style="border: 2px solid rgb(68, 68, 68);; color:rgb(68, 68, 68);">Buyurtma bermoq</a>
					</div>
					</div>
				</div>
			</div>
		</section>


		<section class="container-fluid bg-light pl-3 pr-3 pt-5 pb-5 border-bottom">
			<div class="container p-3">
				<div class="row">
					<div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">
						<h3 class="font-weight-bold">Eng ko'p ko'rilganlar</h3>
					</div>
				</div>
				<div class="row pt-4" id="ads">
					
					{% for obj in recommended_list %}
						<div class="col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 p-3">
							<div class="card rounded profile-card">
								<div class="card-image">
									<span class="card-notify-badge ml-3">{{ obj.category }}</span>
									<!-- Price -->
									{% if obj.free %}
										<span class="card-notify-year">Free</span>
									{% elif obj.discount %}
										<small><del>{{ obj.price }}</del></small>
										<span class="card-notify-year">{{ obj.discount }}</span>
									{% elif obj.price %}
										<span class="card-notify-year">{{ obj.price }}</span>
									{% else %}
										<span class="card-notify-year">Free</span>
									{% endif %}
									<!-- End Price -->

									{% for image in obj.product_image.all %}       
										{% if forloop.counter == 1 %}	
											<img class="img-flu" src="{{ image.imageURL }}" width="100%" height="210" alt="Alternate Text" />
										{% endif %}
									{% endfor %}

								</div>
								<div class="card-body text-center">
									<div class="ad-title m-auto">
										<h6>{{ obj.name|truncatechars:20 }}</h6>
									</div>
								</div>
								<div class="profile-content">
									<ul class="social-link">
										<a href="{{ obj.fileURL }}" onclick="core_method_js(this)" data-slug="{{ obj.slug }}" class="text-white"><i class="fa fa-download fa-2x mr-2"></i></a>
										<a href="{% url 'core:detail' obj.slug %}" class="text-white heartBtn"><i class="fa fa-eye fa-2x mr-2 "></i></a>
										{% if request.user in obj.liked.all %}
											<a  onclick="like_unlike(this)" data-slug="{{ obj.slug }}" class="text-white heartIcon"><i style='color: red;' class="fa fa-heart fa-2x"></i></a>
										{% else %}
											<a onclick="like_unlike(this)" data-slug="{{ obj.slug }}" class="text-white heartIcon"><i class="fa fa-heart fa-2x"></i></a>
										{% endif %}
									</ul>
								</div>
							</div>
						</div>
					{% endfor %}

				</div>
			</div>
		</section>
 
	{% endblock body %}

	{% block js %}
		<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.js' %}"></script>
		<script src="{% static 'js/fakeLoader.min.js' %}"></script>
		<script src="{% static 'js/swiper-bundle.min.js' %}"></script>
		<script src="{% static 'js/script.js' %}"></script>
		<script>
			var mySwiper = new Swiper('.swiper-container',{
			speed: 1000,
			spaceBetween: 0,
			grabCursor:true,
			autoplay:{
				autoplay:true,
				delay:4000,                             
				disableOnInteraction:false         
			}                       
		});

		$(document).ready(function(){
            $('.nav').click(function(e){
                  e.preventDefault();
                  $("#content").load($(this).attr('href'));
            });
      });
		</script>
	{% endblock js %}